#r @"/Users/singampk/.nuget/packages/argu/6.1.1/lib/netstandard2.0/Argu.dll"
#r @"/Users/singampk/.nuget/packages/binance.net/6.12.0/lib/netstandard2.1/Binance.Net.dll"
#r @"/Users/singampk/work/git/bsn_public/trader/Crypto.Shared/bin/Debug/net5.0/Crypto.Shared.dll"
#r @"/Users/singampk/.nuget/packages/cryptoexchange.net/3.7.0/lib/netstandard2.1/CryptoExchange.Net.dll"
#r @"/Users/singampk/.nuget/packages/dapper/2.0.78/lib/net5.0/Dapper.dll"
#r @"/Users/singampk/.nuget/packages/digitalruby.exchangesharp/0.7.4/lib/netstandard2.0/ExchangeSharp.dll"
#r @"/Users/singampk/.nuget/packages/fsharp.control.asyncseq/2.0.21/lib/netstandard2.0/FSharp.Control.AsyncSeq.dll"
#r @"/Users/singampk/.nuget/packages/fsharpx.async/1.14.1/lib/netstandard2.0/FSharpx.Async.dll"
#r @"/Users/singampk/.nuget/packages/fstoolkit.errorhandling/2.2.0/lib/netstandard2.0/FsToolkit.ErrorHandling.dll"
// #r @"/Users/singampk/.nuget/packages/giraffe/4.1.0/lib/netcoreapp3.0/Giraffe.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.aspnet.signalr.client/2.3.0/lib/netstandard1.3/Microsoft.AspNet.SignalR.Client.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Antiforgery.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Authentication.Abstractions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Authentication.Cookies.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Authentication.Core.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Authentication.OAuth.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Authentication.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Authorization.Policy.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Authorization.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Components.Authorization.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Components.Forms.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Components.Server.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Components.Web.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Components.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Connections.Abstractions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.CookiePolicy.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Cors.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Cryptography.Internal.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Cryptography.KeyDerivation.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.DataProtection.Abstractions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.DataProtection.Extensions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.DataProtection.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Diagnostics.Abstractions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Diagnostics.HealthChecks.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Diagnostics.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.HostFiltering.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Hosting.Abstractions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Hosting.Server.Abstractions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.hosting.windowsservices/5.0.3/lib/net5.0/Microsoft.AspNetCore.Hosting.WindowsServices.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Hosting.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Html.Abstractions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Http.Abstractions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Http.Connections.Common.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Http.Connections.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Http.Extensions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Http.Features.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Http.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.HttpOverrides.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.HttpsPolicy.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Identity.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Localization.Routing.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Localization.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Metadata.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Mvc.Abstractions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Mvc.ApiExplorer.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Mvc.Core.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Mvc.Cors.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Mvc.DataAnnotations.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Mvc.Formatters.Json.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Mvc.Formatters.Xml.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Mvc.Localization.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Mvc.Razor.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Mvc.RazorPages.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Mvc.TagHelpers.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Mvc.ViewFeatures.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Mvc.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Razor.Runtime.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Razor.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.ResponseCaching.Abstractions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.ResponseCaching.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.ResponseCompression.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Rewrite.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Routing.Abstractions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Routing.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Server.HttpSys.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Server.IIS.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Server.IISIntegration.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.Core.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.server.kestrel.https/2.2.0/lib/netcoreapp2.1/Microsoft.AspNetCore.Server.Kestrel.Https.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.server.kestrel.transport.abstractions/2.2.0/lib/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.Session.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.SignalR.Common.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.SignalR.Core.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.SignalR.Protocols.Json.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.SignalR.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.StaticFiles.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.WebSockets.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.WebUtilities.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.AspNetCore.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/Microsoft.CSharp.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.dotnet.platformabstractions/2.0.4/lib/netstandard1.3/Microsoft.DotNet.PlatformAbstractions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Caching.Abstractions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Caching.Memory.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration.abstractions/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Configuration.Abstractions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Configuration.Binder.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Configuration.CommandLine.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration.environmentvariables/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Configuration.EnvironmentVariables.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration.fileextensions/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Configuration.FileExtensions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Configuration.Ini.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration.json/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Configuration.Json.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Configuration.KeyPerFile.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Configuration.UserSecrets.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Configuration.Xml.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Configuration.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.dependencyinjection/5.0.1/lib/net5.0/Microsoft.Extensions.DependencyInjection.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.dependencymodel/2.0.4/lib/netstandard1.6/Microsoft.Extensions.DependencyModel.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Diagnostics.HealthChecks.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.FileProviders.Abstractions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.FileProviders.Composite.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.FileProviders.Embedded.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.extensions.fileproviders.physical/5.0.0/lib/netstandard2.0/Microsoft.Extensions.FileProviders.Physical.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.extensions.logging.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Logging.Configuration.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.extensions.logging.configuration/5.0.0/lib/net461/Microsoft.Extensions.Logging.Configuration.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/blazor-devserver.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/Microsoft.Extensions.Hosting.Abstractions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/Microsoft.Extensions.Logging.Abstractions.dll"
// //#r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/x64/aspnetcorev2_inprocess.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/Microsoft.Extensions.Primitives.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/Microsoft.AspNetCore.Components.WebAssembly.Server.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/Microsoft.Extensions.Configuration.Abstractions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/Microsoft.Extensions.Options.dll"
// //#r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/x86/aspnetcorev2_inprocess.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/System.IO.Pipelines.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/Microsoft.Extensions.FileProviders.Abstractions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/Microsoft.Extensions.DependencyInjection.Abstractions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/BlazorDebugProxy/Mono.Cecil.Rocks.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/BlazorDebugProxy/Microsoft.CodeAnalysis.CSharp.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/BlazorDebugProxy/Mono.Cecil.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/BlazorDebugProxy/Microsoft.CodeAnalysis.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/BlazorDebugProxy/BrowserDebugProxy.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/BlazorDebugProxy/Newtonsoft.Json.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/BlazorDebugProxy/Mono.Cecil.Pdb.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/BlazorDebugProxy/BrowserDebugHost.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.FileSystemGlobbing.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Hosting.Abstractions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Hosting.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Http.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Identity.Core.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Identity.Stores.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Localization.Abstractions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Localization.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Logging.Abstractions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Logging.Configuration.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Logging.Console.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Logging.Debug.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Logging.EventLog.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Logging.EventSource.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Logging.TraceSource.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Logging.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.ObjectPool.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Options.ConfigurationExtensions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Options.DataAnnotations.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Options.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.Primitives.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Extensions.WebEncoders.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/blazor-devserver.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/Microsoft.Extensions.Hosting.Abstractions.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/Microsoft.Extensions.Logging.Abstractions.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/Microsoft.Extensions.Primitives.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/Microsoft.AspNetCore.Components.WebAssembly.Server.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/Microsoft.Extensions.Configuration.Abstractions.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/Microsoft.Extensions.Options.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/System.IO.Pipelines.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/Microsoft.Extensions.FileProviders.Abstractions.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/Microsoft.Extensions.DependencyInjection.Abstractions.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/BlazorDebugProxy/Mono.Cecil.Rocks.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/BlazorDebugProxy/Microsoft.CodeAnalysis.CSharp.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/BlazorDebugProxy/Mono.Cecil.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/BlazorDebugProxy/Microsoft.CodeAnalysis.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/BlazorDebugProxy/BrowserDebugProxy.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/BlazorDebugProxy/Newtonsoft.Json.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/BlazorDebugProxy/Mono.Cecil.Pdb.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/5.0.0/tools/BlazorDebugProxy/BrowserDebugHost.dll"
#r @"/Users/singampk/.nuget/packages/microsoft.fsharplu.json/0.11.6/lib/netstandard2.0/Microsoft.FSharpLu.Json.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.io.recyclablememorystream/1.2.2/lib/netstandard1.4/Microsoft.IO.RecyclableMemoryStream.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.JSInterop.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Net.Http.Headers.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/Microsoft.VisualBasic.Core.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/Microsoft.VisualBasic.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/Microsoft.Win32.Primitives.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/Microsoft.Win32.Registry.dll"
// #r @"/Users/singampk/.nuget/packages/nlog/4.5.10/lib/netstandard2.0/NLog.dll"
#r @"/Users/singampk/.nuget/packages/newtonsoft.json/13.0.1/lib/netstandard2.0/Newtonsoft.Json.dll"
// #r @"/Users/singampk/.nuget/packages/npgsql/5.0.3/lib/net5.0/Npgsql.dll"
// #r @"/Users/singampk/.nuget/packages/polly/7.2.2/lib/netstandard2.0/Polly.dll"
// #r @"/Users/singampk/.nuget/packages/restsharp/106.11.7/lib/netstandard2.0/RestSharp.dll"
// #r @"/Users/singampk/.nuget/packages/serilog.aspnetcore/3.4.0/lib/netcoreapp3.1/Serilog.AspNetCore.dll"
// #r @"/Users/singampk/.nuget/packages/serilog.enrichers.assemblyname/1.0.9/lib/netstandard2.0/Serilog.Enrichers.AssemblyName.dll"
// #r @"/Users/singampk/.nuget/packages/serilog.enrichers.context/4.2.0/lib/netcoreapp2.1/Serilog.Enrichers.Context.dll"
// #r @"/Users/singampk/.nuget/packages/serilog.enrichers.environment/2.1.3/lib/netstandard1.5/Serilog.Enrichers.Environment.dll"
// #r @"/Users/singampk/.nuget/packages/serilog.enrichers.process/2.0.1/lib/netstandard1.3/Serilog.Enrichers.Process.dll"
// #r @"/Users/singampk/.nuget/packages/serilog.enrichers.thread/3.1.0/lib/netstandard2.0/Serilog.Enrichers.Thread.dll"
// #r @"/Users/singampk/.nuget/packages/serilog.extensions.hosting/3.1.0/lib/netstandard2.0/Serilog.Extensions.Hosting.dll"
// #r @"/Users/singampk/.nuget/packages/serilog.extensions.logging/3.0.1/lib/netstandard2.0/Serilog.Extensions.Logging.dll"
// #r @"/Users/singampk/.nuget/packages/serilog.formatting.compact/1.1.0/lib/netstandard2.0/Serilog.Formatting.Compact.dll"
// #r @"/Users/singampk/.nuget/packages/serilog.settings.configuration/3.1.0/lib/netstandard2.0/Serilog.Settings.Configuration.dll"
// #r @"/Users/singampk/.nuget/packages/serilog.sinks.console/3.1.1/lib/netcoreapp1.1/Serilog.Sinks.Console.dll"
// #r @"/Users/singampk/.nuget/packages/serilog.sinks.debug/1.0.1/lib/netstandard2.0/Serilog.Sinks.Debug.dll"
// #r @"/Users/singampk/.nuget/packages/serilog.sinks.file/4.1.0/lib/netstandard2.0/Serilog.Sinks.File.dll"
// #r @"/Users/singampk/.nuget/packages/serilog.sinks.periodicbatching/2.3.0/lib/netstandard2.0/Serilog.Sinks.PeriodicBatching.dll"
// #r @"/Users/singampk/.nuget/packages/serilog.sinks.seq/5.0.0/lib/net5.0/Serilog.Sinks.Seq.dll"
// #r @"/Users/singampk/.nuget/packages/serilog/2.10.0/lib/netstandard2.1/Serilog.dll"
// #r @"/Users/singampk/.nuget/packages/supersocket.clientengine.core/0.10.0/lib/netstandard1.3/SuperSocket.ClientEngine.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.AppContext.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Buffers.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Collections.Concurrent.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Collections.Immutable.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Collections.NonGeneric.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Collections.Specialized.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Collections.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.ComponentModel.Annotations.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.ComponentModel.DataAnnotations.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.ComponentModel.EventBasedAsync.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.ComponentModel.Primitives.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.ComponentModel.TypeConverter.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.ComponentModel.dll"
// #r @"/Users/singampk/.nuget/packages/system.configuration.configurationmanager/4.5.0/ref/netstandard2.0/System.Configuration.ConfigurationManager.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Configuration.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Console.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Core.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Data.Common.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Data.DataSetExtensions.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Data.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Diagnostics.Contracts.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Diagnostics.Debug.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Diagnostics.DiagnosticSource.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/System.Diagnostics.EventLog.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Diagnostics.FileVersionInfo.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Diagnostics.Process.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Diagnostics.StackTrace.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Diagnostics.TextWriterTraceListener.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Diagnostics.Tools.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Diagnostics.TraceSource.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Diagnostics.Tracing.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Drawing.Primitives.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Drawing.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Dynamic.Runtime.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Formats.Asn1.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Globalization.Calendars.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Globalization.Extensions.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Globalization.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.IO.Compression.Brotli.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.IO.Compression.FileSystem.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.IO.Compression.ZipFile.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.IO.Compression.dll"
#r @"/Users/singampk/.nuget/packages/system.componentmodel.annotations/5.0.0/ref/netstandard1.1/System.ComponentModel.Annotations.dll"
#r @"/Users/singampk/.nuget/packages/system.componentmodel.annotations/5.0.0/ref/netstandard2.0/System.ComponentModel.Annotations.dll"
#r @"/Users/singampk/.nuget/packages/system.componentmodel.annotations/5.0.0/ref/netstandard2.1/System.ComponentModel.Annotations.dll"
#r @"/Users/singampk/.nuget/packages/system.componentmodel.annotations/5.0.0/ref/netcore50/System.ComponentModel.Annotations.dll"
#r @"/Users/singampk/.nuget/packages/system.componentmodel.annotations/5.0.0/ref/netstandard1.4/System.ComponentModel.Annotations.dll"
#r @"/Users/singampk/.nuget/packages/system.componentmodel.annotations/5.0.0/ref/netstandard1.3/System.ComponentModel.Annotations.dll"
#r @"/Users/singampk/.nuget/packages/system.componentmodel.annotations/5.0.0/ref/net461/System.ComponentModel.Annotations.dll"
#r @"/Users/singampk/.nuget/packages/system.componentmodel.annotations/5.0.0/lib/netstandard2.0/System.ComponentModel.Annotations.dll"
#r @"/Users/singampk/.nuget/packages/system.componentmodel.annotations/5.0.0/lib/netstandard2.1/System.ComponentModel.Annotations.dll"
#r @"/Users/singampk/.nuget/packages/system.componentmodel.annotations/5.0.0/lib/netcore50/System.ComponentModel.Annotations.dll"
#r @"/Users/singampk/.nuget/packages/system.componentmodel.annotations/5.0.0/lib/netstandard1.4/System.ComponentModel.Annotations.dll"
#r @"/Users/singampk/.nuget/packages/system.componentmodel.annotations/5.0.0/lib/net461/System.ComponentModel.Annotations.dll"
#r @"/Users/singampk/.nuget/packages/system.componentmodel.annotations/4.5.0/ref/netstandard1.1/System.ComponentModel.Annotations.dll"
#r @"/Users/singampk/.nuget/packages/system.componentmodel.annotations/4.5.0/ref/netstandard2.0/System.ComponentModel.Annotations.dll"
#r @"/Users/singampk/.nuget/packages/system.componentmodel.annotations/4.5.0/ref/netcore50/System.ComponentModel.Annotations.dll"
#r @"/Users/singampk/.nuget/packages/system.componentmodel.annotations/4.5.0/ref/netstandard1.4/System.ComponentModel.Annotations.dll"
#r @"/Users/singampk/.nuget/packages/system.componentmodel.annotations/4.5.0/ref/netstandard1.3/System.ComponentModel.Annotations.dll"
#r @"/Users/singampk/.nuget/packages/system.componentmodel.annotations/4.5.0/ref/net461/System.ComponentModel.Annotations.dll"
#r @"/Users/singampk/.nuget/packages/system.componentmodel.annotations/4.5.0/lib/netstandard2.0/System.ComponentModel.Annotations.dll"
#r @"/Users/singampk/.nuget/packages/system.componentmodel.annotations/4.5.0/lib/netcore50/System.ComponentModel.Annotations.dll"
#r @"/Users/singampk/.nuget/packages/system.componentmodel.annotations/4.5.0/lib/netstandard1.4/System.ComponentModel.Annotations.dll"
#r @"/Users/singampk/.nuget/packages/system.componentmodel.annotations/4.5.0/lib/net461/System.ComponentModel.Annotations.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.IO.FileSystem.DriveInfo.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.IO.FileSystem.Primitives.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.IO.FileSystem.Watcher.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.IO.FileSystem.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.IO.IsolatedStorage.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.IO.MemoryMappedFiles.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/System.IO.Pipelines.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.IO.Pipes.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.IO.UnmanagedMemoryStream.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.IO.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Linq.Expressions.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Linq.Parallel.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Linq.Queryable.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Linq.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Memory.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Net.Http.Json.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Net.Http.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Net.HttpListener.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Net.Mail.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Net.NameResolution.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Net.NetworkInformation.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Net.Ping.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Net.Primitives.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Net.Requests.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Net.Security.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Net.ServicePoint.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Net.Sockets.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Net.WebClient.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Net.WebHeaderCollection.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Net.WebProxy.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Net.WebSockets.Client.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Net.WebSockets.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Net.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Numerics.Vectors.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Numerics.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.ObjectModel.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Reflection.DispatchProxy.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Reflection.Emit.ILGeneration.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Reflection.Emit.Lightweight.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Reflection.Emit.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Reflection.Extensions.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Reflection.Metadata.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Reflection.Primitives.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Reflection.TypeExtensions.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Reflection.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Resources.Reader.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Resources.ResourceManager.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Resources.Writer.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Runtime.CompilerServices.Unsafe.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Runtime.CompilerServices.VisualC.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Runtime.Extensions.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Runtime.Handles.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Runtime.InteropServices.RuntimeInformation.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Runtime.InteropServices.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Runtime.Intrinsics.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Runtime.Loader.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Runtime.Numerics.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Runtime.Serialization.Formatters.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Runtime.Serialization.Json.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Runtime.Serialization.Primitives.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Runtime.Serialization.Xml.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Runtime.Serialization.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Runtime.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/System.Security.AccessControl.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Security.Claims.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Security.Cryptography.Algorithms.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/System.Security.Cryptography.Cng.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Security.Cryptography.Csp.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Security.Cryptography.Encoding.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Security.Cryptography.Primitives.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Security.Cryptography.X509Certificates.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/System.Security.Cryptography.Xml.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/System.Security.Permissions.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/System.Security.Principal.Windows.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Security.Principal.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Security.SecureString.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Security.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.ServiceModel.Web.dll"
// #r @"/Users/singampk/.nuget/packages/system.serviceprocess.servicecontroller/5.0.0/ref/netstandard2.0/System.ServiceProcess.ServiceController.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.ServiceProcess.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Text.Encoding.CodePages.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Text.Encoding.Extensions.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Text.Encoding.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Text.Encodings.Web.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Text.Json.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Text.RegularExpressions.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Threading.Channels.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Threading.Overlapped.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Threading.Tasks.Dataflow.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Threading.Tasks.Extensions.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Threading.Tasks.Parallel.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Threading.Tasks.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Threading.Thread.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Threading.ThreadPool.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Threading.Timer.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Threading.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Transactions.Local.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Transactions.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.ValueTuple.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Web.HttpUtility.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Web.dll"
// #r @"/Users/singampk/.nuget/packages/microsoft.extensions.configuration/5.0.0/lib/netstandard2.0/System.Windows.Extensions.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Windows.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Xml.Linq.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Xml.ReaderWriter.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Xml.Serialization.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Xml.XDocument.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Xml.XPath.XDocument.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Xml.XPath.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Xml.XmlDocument.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Xml.XmlSerializer.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.Xml.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/System.dll"
// #r @"/Users/singampk/.nuget/packages/taskbuilder.fs/2.1.0/lib/netstandard1.6/TaskBuilder.fs.dll"
// #r @"/Users/singampk/.nuget/packages/utf8json/1.3.7/lib/netstandard2.0/Utf8Json.dll"
// #r @"/Users/singampk/.nuget/packages/websocket4net/0.15.2/lib/netstandard1.3/WebSocket4Net.dll"
// #r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/WindowsBase.dll"
#r @"/Users/singampk/.nuget/packages/bybit-api-client/1.0.0/lib/net5.0/bybit-api-client.dll"
//#r @"C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref/5.0.0/ref/net5.0/netstandard.dll"
#load @"/Users/singampk/work/git/bsn_public/trader/Crypto.Trader/Types.fs"
#load @"/Users/singampk/work/git/bsn_public/trader/Crypto.Trader/AnalysisTypes.fs"
#load @"/Users/singampk/work/git/bsn_public/trader/Crypto.Trader/Exchanges/Exchanges.fs"
// #load @"/Users/singampk/work/git/bsn_public/trader/Crypto.Trader/Exchanges/Binance/ApiTypes.fs"
// #load @"/Users/singampk/work/git/bsn_public/trader/Crypto.Trader/Exchanges/Binance/Spot/Trade.fs"
// #load @"/Users/singampk/work/git/bsn_public/trader/Crypto.Trader/Exchanges/Binance/Futures/Trade.fs"
#load @"/Users/singampk/work/git/bsn_public/trader/Crypto.Trader/Exchanges/Bybit/Futures/ApiClient.fs"
#load @"/Users/singampk/work/git/bsn_public/trader/Crypto.Trader/Exchanges/Bybit/Futures/Trade.fs"
#load @"/Users/singampk/work/git/bsn_public/trader/Crypto.Trader/Exchanges/Bybit/Futures/Market.fs"
// #load @"/Users/singampk/work/git/bsn_public/trader/Crypto.Trader/Exchanges/Simulator/Exchange.fs"
// #load @"/Users/singampk/work/git/bsn_public/trader/Crypto.Trader/FuturesTrade.fs"
// #load @"/Users/singampk/work/git/bsn_public/trader/Crypto.Trader/SpotTrade.fs"
// #load @"/Users/singampk/work/git/bsn_public/trader/Crypto.Trader/Db.fs"
// #load @"/Users/singampk/work/git/bsn_public/trader/Crypto.Trader/Positions.fs"
// #load @"/Users/singampk/work/git/bsn_public/trader/Crypto.Trader/WebApi.fs"
// #load @"/Users/singampk/work/git/bsn_public/trader/Crypto.Trader/Program.fs"