CREATE OR REPLACE VIEW public.overview_buy_analysis
  AS SELECT e.name AS exchange_name,
       positive_signal.signal_id,
       positive_signal.strategy,
            timezone('Australia/Sydney'::text, timezone('utc'::text, positive_signal.buy_signal_date_time)) AS buy_signal_date_time,
            timezone('Australia/Sydney'::text, timezone('utc'::text, positive_signal.buy_date_time)) AS buy_date_time,
       positive_signal.symbol,
       positive_signal.buy_price,
       positive_signal.actual_buy_price,
       positive_signal.sell_price,
       positive_signal.actual_sell_price,
       positive_signal.status,
       timezone('Australia/Sydney'::text, timezone('utc'::text, positive_signal.sell_signal_date_time)) AS sell_signal_date_time,
       timezone('Australia/Sydney'::text, timezone('utc'::text, positive_signal.sell_date_time)) AS sell_date_time,
       (positive_signal.sell_price - positive_signal.buy_price) / positive_signal.buy_price * 100::numeric AS signal_sold_gain_percent,
       (positive_signal.actual_sell_price - positive_signal.actual_buy_price) / positive_signal.buy_price * 100::numeric AS actual_sold_gain_percent,
       b.last_mins_neg_flow,
       b.price_movement_percent AS pricemovpercent,
       b.rsi,
       b.bolen_avg,
       b.change45min,
       b.curr_by_bolenger,
       b.curr_by_lowest,
       b.div_dip,
       b.first_resistance,
       b.second_resistance,
       b.moving_agv60min AS movingavg60min,
       b.first_support,
       b.second_support,
       b.standard_deviation,
       b.tick_high,
       b.tick_low,
       b.waited_average,
       b.largeema,
       b.medema,
       b.smallema,
       b.moving_averageb2 AS movingaverage30minbefore,
       b.moving_averageb3 AS movingaverage1hrbefore,
       b.moving_average30min AS movingavgfrombuyanalysis,
       b.tick_high_24hr,
       b.tick_low_24hr
     FROM positive_signal
       JOIN exchange e ON positive_signal.exchange_id = e.id
       LEFT JOIN coin_24hr_market ON positive_signal.symbol::text = coin_24hr_market.symbol::text
       LEFT JOIN buy_analysis b ON positive_signal.signal_id = b.signal_id
     ORDER BY (timezone('Australia/Sydney'::text, timezone('utc'::text, positive_signal.buy_signal_date_time))) DESC;
